# Generated by Django 6.0.2 on 2026-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_URL_Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheck',
            name='user_feedback',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
